version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing dependencies..."
      - npm install

  pre_build:
    commands:
      - echo "Setting up environment variables..."
      - echo "DB_URL=$DB_URL" >> .env
      - echo "DB_USERNAME=$DB_USERNAME" >> .env
      - echo "DB_PASSWORD=$DB_PASSWORD" >> .env

  build:
    commands:
      - echo "Build started on `date`"
      - npm run build
      - echo "Build completed on `date`"

  post_build:
    commands:
      - echo "Post-build steps"
      - ls -l
      - echo "Build completed. Preparing to deploy."

artifacts:
  files:
    - appspec.yml
    - dist/**
    - scripts/*
  discard-paths: yes

cache:
  paths:
    - node_modules/**/*